<?xml version="1.0" encoding="utf-8"?>
<robot name="boxbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find boxbot_description)/urdf/boxbot.gazebo"/>

    <!-- height -> Z direction; width -> Y direction; length -> X direction; Unit: m-->
    <xacro:property name="base_height" value="0.31794"/>
    <xacro:property name="base_width" value="1.2"/>
    <xacro:property name="base_length" value="0.8"/>

    <xacro:property name="tower_height" value="2.01"/>
    <xacro:property name="tower_width" value="0.35"/>
    <xacro:property name="tower_length" value="0.35"/>

    <xacro:property name="arm_height" value="0.31341"/>
    <xacro:property name="arm_width" value="1.78014"/>
    <xacro:property name="arm_length" value="0.14155"/>

    <xacro:property name="wrist_height" value="0.15205"/>
    <xacro:property name="wrist_width" value="0.09925"/>
    <xacro:property name="wrist_length" value="0.082"/>

    <xacro:property name="hand_height" value="0.13"/>
    <xacro:property name="hand_width" value="0.01"/>
    <xacro:property name="hand_length" value="0.01"/>

    <xacro:property name="gripper_height" value="0.27197"/>
    <xacro:property name="gripper_width" value="0.49013"/>
    <xacro:property name="gripper_length" value="0.3762"/>

    <xacro:property name="base_origin">
		<origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
	</xacro:property>
    
    <xacro:property name="tower_origin">
        <origin xyz="0 0 ${tower_height / 2}" rpy="0 0 0"/>
    </xacro:property>

    <xacro:property name="arm_origin">
        <origin xyz="0.038 0.34207 ${arm_height / 2}" rpy ="0 0 0"/>
    </xacro:property>

    <xacro:property name="wrist_origin">
        <origin xyz="0.02225 0 -0.01975" rpy ="0 0 0"/>
    </xacro:property>

    <xacro:property name="hand_origin">
        <origin xyz="0 0 -${hand_height / 2}" rpy ="0 0 0"/>
    </xacro:property>

    <xacro:property name="gripper_origin">
        <origin xyz="-0.0109 0 -${gripper_height / 2 + 0.001}" rpy ="0 0 0"/>
    </xacro:property>

    <link name="world"/>

    <joint name="virtual_joint" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
        


    <link name="base_link">
        <inertial>
            <origin xyz="1.21161602598674E-05 -0.000141697234924631 0.115075250920086" 
                rpy="0 0 0" />
        <mass value="42.7823329299279" />
        <inertia ixx="2.3137133186018" ixy="0.0758431395924076" ixz="-1.56977697384168E-07"
                iyy="1.43328003600734" iyz="1.83584220863051E-06"
                izz="3.73773799217461" />
        </inertial>
        <visual>
            <xacro:insert_block name="base_origin"/>
            <geometry>
            <mesh filename="package://boxbot_description/meshes/base_link.STL" />
            </geometry>
            <material name="">
            <color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
            </material>
        </visual>
        <collision>
            <xacro:insert_block name="base_origin"/>
            <geometry>
            <mesh filename="package://boxbot_description/meshes/base_link.STL" />
            </geometry>
        </collision>
    </link>
        
    <link name="tower_link">
        <inertial>
        <origin xyz="-0.00148764220555564 -0.00430184829877756 0.780186947697388" rpy="0 0 0" />
        <mass value="32.2621346397055" />
        <inertia ixx="5.83539245387147" ixy="0.000842169945369176" ixz="0.00017449730709294"
                iyy="5.79696379893898" iyz="0.000216570416594675"
                izz="0.0782122151057882" />
        </inertial>
        <visual>
            <xacro:insert_block name="tower_origin"/>
            <geometry>
            <mesh filename="package://boxbot_description/meshes/tower_link.STL" />
            </geometry>
            <material name="">
                <color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
            </material>
        </visual>
        <collision>
            <xacro:insert_block name="tower_origin"/>
        <geometry>
            <mesh filename="package://boxbot_description/meshes/tower_link.STL" />
        </geometry>
        </collision>
    </link>

    <joint name="base_tower_joint" type="revolute">
        <origin xyz="0 0 0.3145" rpy="0 0 0.051195" />
        <parent link="base_link" />
        <child link="tower_link" />
        <axis xyz="0 0 1" />
        <limit lower="-3.14" upper="3.14" effort="100" velocity="0.3" />
    </joint>



    <link name="arm_link">
        <inertial>
        <origin xyz="0.038387800107173 0.392080597458587 0.106253703611536" rpy="0 0 0" />
        <mass value="7.90977803912173" />
        <inertia ixx="1.3964597770644" ixy="-0.00570272799674222" ixz="0.00312455918060977"
                iyy="0.0281361548287597" iyz="0.0390219048580493"
                izz="1.37349990251812" />
        </inertial>
        <visual>
            <xacro:insert_block name="arm_origin"/>
            <geometry>
                <mesh filename="package://boxbot_description/meshes/arm_link.STL" />
            </geometry>
            <material name="">
                <color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
            </material>
        </visual>
        <collision>
            <xacro:insert_block name="arm_origin"/>
            <geometry>
                <mesh filename="package://boxbot_description/meshes/arm_link.STL" />
            </geometry>
        </collision>
    </link>

    <joint name="tower_arm_joint" type="prismatic">
        <origin xyz="0.0599999999997043 0.0269999999998549 0.1372182458184" rpy="0 0 0" />
        <parent link="tower_link" />
        <child link="arm_link" />
        <axis xyz="0 0 1" />
        <limit lower="0" upper="1.57" effort="100" velocity="0.179" />
    </joint>

    
    <link name="wrist_link">
        <inertial>
            <origin xyz="0.0310886914761871 -0.00055357042962885 -0.0008145171529782" rpy="0 0 0" />
            <mass value="0.252648442993223" />
        <inertia ixx="0.000406659062862429" ixy="-1.29227360078791E-07" ixz="-3.09220823927946E-06"
                iyy="0.000344866185048593" iyz="6.17525359286755E-07"
                izz="0.000152631223532851" />
        </inertial>
        <visual>
            <xacro:insert_block name="wrist_origin"/>
            <geometry>
                <mesh filename="package://boxbot_description/meshes/wrist_link.STL" />
            </geometry>
            <material name="">
                <color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
            </material>
        </visual>
        <collision>
            <xacro:insert_block name="wrist_origin"/>
            <geometry>
                <mesh filename="package://boxbot_description/meshes/wrist_link.STL" />
            </geometry>
        </collision>
    </link>

    <joint name="arm_wrist_joint" type="prismatic">
        <origin xyz="0.0339999999999955 ${1.09131998351706 - 0.0821} 0.108999999999999" rpy="0 0 0" />
        <parent link="arm_link" />
        <child link="wrist_link" />
        <axis xyz="0 -1 0" />
        <limit lower="0" upper="${0.88 - 0.0821}" effort="100" velocity="0.179" />
    </joint>


    <link name="hand_link">
        <inertial>
        <origin xyz="-7.35310108845866E-06 -1.60996144753234E-06 -0.0649812985906855" rpy="0 0 0" />
        <mass value="0.0101760116822838" />
        <inertia ixx="1.43633392907582E-05" ixy="6.35605424668044E-11" ixz="-3.55573648010034E-09"
            iyy="1.4363062814601E-05" iyz="-7.78714263202763E-10"
            izz="1.26970538556033E-07" />
        </inertial>
        <visual>
            <xacro:insert_block name="hand_origin"/>
            <geometry>
                <mesh filename="package://boxbot_description/meshes/hand_link.STL" />
            </geometry>
            <material name="">
                <color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
            </material>
        </visual>
        <collision>
            <xacro:insert_block name="hand_origin"/>
            <geometry>
                <mesh filename="package://boxbot_description/meshes/hand_link.STL" />
            </geometry>
        </collision>
    </link>


    <joint name="wrist_hand_joint" type="revolute">
        <origin xyz="0.0465 -0.00915 -0.0018" rpy="0 0 0" />
        <parent link="wrist_link" />
        <child link="hand_link" />
        <axis xyz="0 0 1" />
        <limit lower="-1.57" upper="1.57" effort="100" velocity="0.63" />
    </joint>



    <link name="gripper_link">
	    <inertial>
		    <origin xyz="-0.0032546411241845 -0.000648008057776719 -0.110079171281878" rpy="0 0 0" />
		    <mass value="0.72267856807254" /> 
		    <inertia ixx="0.0289006606354982" ixy="-1.66588317728096E-09" ixz="0.000784548491452252"
			    iyy="0.0110294748047172" iyz="7.89243454897512E-09"
			    izz="0.0263921467919252" />
	    </inertial>
	    <visual>
		    <xacro:insert_block name="gripper_origin"/>
		    <geometry>
			    <mesh filename="package://boxbot_description/meshes/gripper_link.STL" />
		    </geometry>
		    <material name="">
			    <color rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
		    </material>
	    </visual>
	    <collision>
		    <xacro:insert_block name="gripper_origin"/>
		    <geometry>
			    <mesh filename="package://boxbot_description/meshes/gripper_link.STL" />
		    </geometry>
	    </collision>
    </link>

    <joint name="hand_gripper_joint" type="fixed">
	    <origin xyz="0 0 -0.094247" rpy="0 0 0" />
	    <parent link="hand_link" />
	    <child link="gripper_link" />
	    <axis xyz="0 0 0" />
    </joint>

    <transmission name="tran1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_tower_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="base_tower_joint_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    
    <transmission name="tran2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="tower_arm_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="tower_arm_joint_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    
    <transmission name="tran3">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="arm_wrist_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="arm_wrist_joint_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!--<transmission name="tran4">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="wrist_hand_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="wrist_hand_joint_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>-->
</robot>
























